### ISSUE TITLE
Fildo Taken Down / Closed on 16 April ..!! is this Legit .. ?!!

### ISSUE THREAD

**Issue by FurqanHanif** [SergioZgz/Fildo#2]
Hello .. !!
As far as i Know , Fildo is Taken Down by Owner on 16 April , But on fildo.net app is STill Up-dating but here No Comits or Files are Updated... 
So is this App Legit , Fake or What .. ??
Thanks

**Comment by SergioZgz** [comment]
App is legit, Fildo website was closed on 16 april, and I published the code of android app... because a lot of people ask for that but nobody did a new release or fix anything.

Then I continue only fixing or adding some easy features to it and only when have free time...  which is why so not out new versions for a few months...

Fildo website never will be opened again, fildo android app can be abandoned any day, when I leave the project will post my latest code.
